-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS nimbusbd.audit_log DROP CONSTRAINT IF EXISTS audit_log_user_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.course_enrollments DROP CONSTRAINT IF EXISTS course_enrollments_course_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.course_enrollments DROP CONSTRAINT IF EXISTS course_enrollments_user_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.courses DROP CONSTRAINT IF EXISTS courses_mentor_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.placement_decisions DROP CONSTRAINT IF EXISTS placement_decisions_physical_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.placement_decisions DROP CONSTRAINT IF EXISTS placement_decisions_slice_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.placement_decisions DROP CONSTRAINT IF EXISTS placement_decisions_vm_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.sessions DROP CONSTRAINT IF EXISTS sessions_user_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slice_access DROP CONSTRAINT IF EXISTS slice_access_slice_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slice_access DROP CONSTRAINT IF EXISTS slice_access_user_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slice_events DROP CONSTRAINT IF EXISTS slice_events_slice_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slice_events DROP CONSTRAINT IF EXISTS slice_events_triggered_by_fkey;

ALTER TABLE IF EXISTS nimbusbd.slice_templates DROP CONSTRAINT IF EXISTS slice_templates_created_by_fkey;

ALTER TABLE IF EXISTS nimbusbd.slices DROP CONSTRAINT IF EXISTS slices_course_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slices DROP CONSTRAINT IF EXISTS slices_owner_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slices DROP CONSTRAINT IF EXISTS slices_physical_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.slices DROP CONSTRAINT IF EXISTS slices_template_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.topology_links DROP CONSTRAINT IF EXISTS topology_links_slice_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.topology_links DROP CONSTRAINT IF EXISTS topology_links_source_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.topology_links DROP CONSTRAINT IF EXISTS topology_links_target_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.topology_nodes DROP CONSTRAINT IF EXISTS topology_nodes_slice_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.vm_configs DROP CONSTRAINT IF EXISTS vm_configs_image_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.vm_configs DROP CONSTRAINT IF EXISTS vm_configs_node_id_fkey;

ALTER TABLE IF EXISTS nimbusbd.vm_metrics_current DROP CONSTRAINT IF EXISTS vm_metrics_current_node_id_fkey;



DROP TABLE IF EXISTS nimbusbd.audit_log;

CREATE TABLE IF NOT EXISTS nimbusbd.audit_log
(
    id bigserial NOT NULL,
    user_id uuid,
    action character varying(80) COLLATE pg_catalog."default" NOT NULL,
    resource_type character varying(60) COLLATE pg_catalog."default",
    resource_id uuid,
    metadata jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.course_enrollments;

CREATE TABLE IF NOT EXISTS nimbusbd.course_enrollments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    course_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT course_enrollments_pkey PRIMARY KEY (id),
    CONSTRAINT course_enrollments_course_id_user_id_key UNIQUE (course_id, user_id)
);

DROP TABLE IF EXISTS nimbusbd.courses;

CREATE TABLE IF NOT EXISTS nimbusbd.courses
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    mentor_id uuid,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_code_key UNIQUE (code)
);

DROP TABLE IF EXISTS nimbusbd.physical_metrics_current;

CREATE TABLE IF NOT EXISTS nimbusbd.physical_metrics_current
(

    CONSTRAINT physical_metrics_current_physical_node_id_key UNIQUE (physical_node_id)
);

DROP TABLE IF EXISTS nimbusbd.physical_nodes;

CREATE TABLE IF NOT EXISTS nimbusbd.physical_nodes
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    hostname character varying(120) COLLATE pg_catalog."default" NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default" NOT NULL,
    cluster_type nimbusbd.cluster_type NOT NULL,
    status nimbusbd.physical_status NOT NULL DEFAULT 'online'::nimbusbd.physical_status,
    cpu_cores real NOT NULL,
    ram_mb bigint NOT NULL,
    disk_gb bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT physical_nodes_pkey PRIMARY KEY (id),
    CONSTRAINT physical_nodes_hostname_key UNIQUE (hostname)
);

DROP TABLE IF EXISTS nimbusbd.placement_decisions;

CREATE TABLE IF NOT EXISTS nimbusbd.placement_decisions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    slice_id uuid NOT NULL,
    vm_node_id uuid NOT NULL,
    physical_node_id uuid NOT NULL,
    algorithm_used character varying(40) COLLATE pg_catalog."default",
    score real,
    resource_snapshot jsonb,
    decided_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT placement_decisions_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.sessions;

CREATE TABLE IF NOT EXISTS nimbusbd.sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sessions_pkey PRIMARY KEY (id),
    CONSTRAINT sessions_token_hash_key UNIQUE (token_hash)
);

DROP TABLE IF EXISTS nimbusbd.slice_access;

CREATE TABLE IF NOT EXISTS nimbusbd.slice_access
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    slice_id uuid NOT NULL,
    user_id uuid NOT NULL,
    permission nimbusbd.slice_permission NOT NULL DEFAULT 'viewer'::nimbusbd.slice_permission,
    granted_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT slice_access_pkey PRIMARY KEY (id),
    CONSTRAINT slice_access_slice_id_user_id_key UNIQUE (slice_id, user_id)
);

DROP TABLE IF EXISTS nimbusbd.slice_events;

CREATE TABLE IF NOT EXISTS nimbusbd.slice_events
(
    id bigserial NOT NULL,
    slice_id uuid NOT NULL,
    triggered_by uuid,
    event_type nimbusbd.slice_event_type NOT NULL,
    message text COLLATE pg_catalog."default",
    payload jsonb,
    occurred_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT slice_events_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.slice_templates;

CREATE TABLE IF NOT EXISTS nimbusbd.slice_templates
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_by uuid,
    topology_definition jsonb NOT NULL DEFAULT '{}'::jsonb,
    vm_count integer NOT NULL DEFAULT 0,
    link_count integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT slice_templates_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.slices;

CREATE TABLE IF NOT EXISTS nimbusbd.slices
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    course_id uuid,
    template_id uuid,
    owner_id uuid,
    status nimbusbd.slice_status NOT NULL DEFAULT 'pending'::nimbusbd.slice_status,
    availability_zone character varying(60) COLLATE pg_catalog."default",
    physical_node_id uuid,
    placement_metadata jsonb,
    started_at timestamp with time zone,
    stopped_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT slices_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.topology_links;

CREATE TABLE IF NOT EXISTS nimbusbd.topology_links
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    slice_id uuid NOT NULL,
    source_node_id uuid NOT NULL,
    target_node_id uuid NOT NULL,
    vlan_id character varying(20) COLLATE pg_catalog."default",
    network_name character varying(120) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT topology_links_pkey PRIMARY KEY (id),
    CONSTRAINT topology_links_slice_id_source_node_id_target_node_id_key UNIQUE (slice_id, source_node_id, target_node_id)
);

DROP TABLE IF EXISTS nimbusbd.topology_nodes;

CREATE TABLE IF NOT EXISTS nimbusbd.topology_nodes
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    slice_id uuid NOT NULL,
    label character varying(80) COLLATE pg_catalog."default" NOT NULL,
    node_type nimbusbd.node_type NOT NULL DEFAULT 'server'::nimbusbd.node_type,
    cluster_id character varying(120) COLLATE pg_catalog."default",
    state nimbusbd.node_state NOT NULL DEFAULT 'pending'::nimbusbd.node_state,
    pos_x real,
    pos_y real,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT topology_nodes_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS nimbusbd.users;

CREATE TABLE IF NOT EXISTS nimbusbd.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role nimbusbd.user_role NOT NULL DEFAULT 'usuario'::nimbusbd.user_role,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

DROP TABLE IF EXISTS nimbusbd.vm_configs;

CREATE TABLE IF NOT EXISTS nimbusbd.vm_configs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    node_id uuid NOT NULL,
    flavor character varying(60) COLLATE pg_catalog."default",
    disk_gb integer,
    image_id uuid,
    keypair_name character varying(80) COLLATE pg_catalog."default",
    security_rules jsonb NOT NULL DEFAULT '[]'::jsonb,
    extra_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vm_configs_pkey PRIMARY KEY (id),
    CONSTRAINT vm_configs_node_id_key UNIQUE (node_id)
);

DROP TABLE IF EXISTS nimbusbd.vm_images;

CREATE TABLE IF NOT EXISTS nimbusbd.vm_images
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    os_family character varying(60) COLLATE pg_catalog."default",
    version character varying(40) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    url character varying NOT NULL,
    CONSTRAINT vm_images_pkey PRIMARY KEY (id),
    CONSTRAINT vm_images_name_key UNIQUE (name)
);

DROP TABLE IF EXISTS nimbusbd.vm_metrics_current;

CREATE TABLE IF NOT EXISTS nimbusbd.vm_metrics_current
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    node_id uuid NOT NULL,
    cpu_pct real,
    ram_pct real,
    net_in_mbps real,
    net_out_mbps real,
    disk_used_pct real,
    vm_status nimbusbd.vm_status,
    sampled_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vm_metrics_current_pkey PRIMARY KEY (id),
    CONSTRAINT vm_metrics_current_node_id_key UNIQUE (node_id)
);

ALTER TABLE IF EXISTS nimbusbd.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id
    ON nimbusbd.audit_log(user_id);


ALTER TABLE IF EXISTS nimbusbd.course_enrollments
    ADD CONSTRAINT course_enrollments_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES nimbusbd.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollments_course_id
    ON nimbusbd.course_enrollments(course_id);


ALTER TABLE IF EXISTS nimbusbd.course_enrollments
    ADD CONSTRAINT course_enrollments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollments_user_id
    ON nimbusbd.course_enrollments(user_id);


ALTER TABLE IF EXISTS nimbusbd.courses
    ADD CONSTRAINT courses_mentor_id_fkey FOREIGN KEY (mentor_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_courses_mentor_id
    ON nimbusbd.courses(mentor_id);


ALTER TABLE IF EXISTS nimbusbd.placement_decisions
    ADD CONSTRAINT placement_decisions_physical_node_id_fkey FOREIGN KEY (physical_node_id)
    REFERENCES nimbusbd.physical_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_placement_physical_node
    ON nimbusbd.placement_decisions(physical_node_id);


ALTER TABLE IF EXISTS nimbusbd.placement_decisions
    ADD CONSTRAINT placement_decisions_slice_id_fkey FOREIGN KEY (slice_id)
    REFERENCES nimbusbd.slices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_placement_slice_id
    ON nimbusbd.placement_decisions(slice_id);


ALTER TABLE IF EXISTS nimbusbd.placement_decisions
    ADD CONSTRAINT placement_decisions_vm_node_id_fkey FOREIGN KEY (vm_node_id)
    REFERENCES nimbusbd.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS nimbusbd.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON nimbusbd.sessions(user_id);


ALTER TABLE IF EXISTS nimbusbd.slice_access
    ADD CONSTRAINT slice_access_slice_id_fkey FOREIGN KEY (slice_id)
    REFERENCES nimbusbd.slices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS nimbusbd.slice_access
    ADD CONSTRAINT slice_access_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_slice_access_user_id
    ON nimbusbd.slice_access(user_id);


ALTER TABLE IF EXISTS nimbusbd.slice_events
    ADD CONSTRAINT slice_events_slice_id_fkey FOREIGN KEY (slice_id)
    REFERENCES nimbusbd.slices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_slice_events_slice_id
    ON nimbusbd.slice_events(slice_id);


ALTER TABLE IF EXISTS nimbusbd.slice_events
    ADD CONSTRAINT slice_events_triggered_by_fkey FOREIGN KEY (triggered_by)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS nimbusbd.slice_templates
    ADD CONSTRAINT slice_templates_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS nimbusbd.slices
    ADD CONSTRAINT slices_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES nimbusbd.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_slices_course_id
    ON nimbusbd.slices(course_id);


ALTER TABLE IF EXISTS nimbusbd.slices
    ADD CONSTRAINT slices_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES nimbusbd.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_slices_owner_id
    ON nimbusbd.slices(owner_id);


ALTER TABLE IF EXISTS nimbusbd.slices
    ADD CONSTRAINT slices_physical_node_id_fkey FOREIGN KEY (physical_node_id)
    REFERENCES nimbusbd.physical_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_slices_physical_node
    ON nimbusbd.slices(physical_node_id);


ALTER TABLE IF EXISTS nimbusbd.slices
    ADD CONSTRAINT slices_template_id_fkey FOREIGN KEY (template_id)
    REFERENCES nimbusbd.slice_templates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS nimbusbd.topology_links
    ADD CONSTRAINT topology_links_slice_id_fkey FOREIGN KEY (slice_id)
    REFERENCES nimbusbd.slices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_topo_links_slice_id
    ON nimbusbd.topology_links(slice_id);


ALTER TABLE IF EXISTS nimbusbd.topology_links
    ADD CONSTRAINT topology_links_source_node_id_fkey FOREIGN KEY (source_node_id)
    REFERENCES nimbusbd.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_topo_links_source
    ON nimbusbd.topology_links(source_node_id);


ALTER TABLE IF EXISTS nimbusbd.topology_links
    ADD CONSTRAINT topology_links_target_node_id_fkey FOREIGN KEY (target_node_id)
    REFERENCES nimbusbd.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_topo_links_target
    ON nimbusbd.topology_links(target_node_id);


ALTER TABLE IF EXISTS nimbusbd.topology_nodes
    ADD CONSTRAINT topology_nodes_slice_id_fkey FOREIGN KEY (slice_id)
    REFERENCES nimbusbd.slices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_topo_nodes_slice_id
    ON nimbusbd.topology_nodes(slice_id);


ALTER TABLE IF EXISTS nimbusbd.vm_configs
    ADD CONSTRAINT vm_configs_image_id_fkey FOREIGN KEY (image_id)
    REFERENCES nimbusbd.vm_images (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS nimbusbd.vm_configs
    ADD CONSTRAINT vm_configs_node_id_fkey FOREIGN KEY (node_id)
    REFERENCES nimbusbd.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS vm_configs_node_id_key
    ON nimbusbd.vm_configs(node_id);


ALTER TABLE IF EXISTS nimbusbd.vm_metrics_current
    ADD CONSTRAINT vm_metrics_current_node_id_fkey FOREIGN KEY (node_id)
    REFERENCES nimbusbd.topology_nodes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS vm_metrics_current_node_id_key
    ON nimbusbd.vm_metrics_current(node_id);

END;